# Generated by Django 5.2.8 on 2025-11-24 05:40

from django.db import migrations
import random

def update_product_names(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    
    clothing_names = [
        "Classic Cotton T-Shirt", "Slim Fit Denim Jeans", "V-Neck Cashmere Sweater", "Linen Button-Up Shirt",
        "Chino Trousers", "Floral Summer Dress", "Quilted Puffer Jacket", "Wool Blend Peacoat",
        "Graphic Print Hoodie", "Silk Camisole Top", "High-Waisted Skinny Jeans", "Pleated Midi Skirt",
        "Leather Biker Jacket", "Turtleneck Knit Sweater", "Denim Cut-off Shorts", "Bohemian Maxi Dress",
        "Striped Crewneck T-Shirt", "Corduroy Straight-Leg Pants", "Cable-Knit Cardigan", "Plaid Flannel Shirt",
        "Ankle-Grazer Trousers", "Ruffled Wrap Dress", "Faux Fur-Trimmed Parka", "Double-Breasted Trench Coat",
        "Embroidered Bomber Jacket", "Lace-Trimmed Slip Dress", "Distressed Boyfriend Jeans", "A-Line Denim Skirt",
        "Suede Moto Jacket", "Oversized Knit Jumper", "Drawstring Linen Shorts", "Polka Dot Sundress",
        "Vintage Wash T-Shirt", "Cropped Wide-Leg Jeans", "Chunky Knit-Turtleneck", "Utility Jumpsuit",
        "Sequin Party Dress", "Velvet Blazer", "Pinstripe Trousers", "Satin Midi Dress", "Tweed Mini Skirt",
        "Fringed Kimono", "Ribbed Tank Top", "Cargo Pants", "Cashmere Scarf", "Leather Gloves",
        "Fedora Hat", "Canvas Tote Bag"
    ]

    products = list(Product.objects.all())
    for product in products:
        product.name = random.choice(clothing_names)
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_product_names),
    ]